#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/import_env.sh"

echo "CERT_MANAGER_EMAIL: ${CERT_MANAGER_EMAIL}"
echo "CERT_MANAGER_VERSION: ${CERT_MANAGER_VERSION}"
echo "CERT_MANAGER_NAMESPACE: ${CERT_MANAGER_NAMESPACE}"
echo "CERT_MANAGER_RELEASE: ${CERT_MANAGER_RELEASE}"
echo "CERT_MANAGER_ACME_SERVER: ${CERT_MANAGER_ACME_SERVER}"
echo "CERT_MANAGER_INGRESS_CLASS: ${CERT_MANAGER_INGRESS_CLASS}"
echo "CERT_MANAGER_DELETE_NAMESPACE: ${CERT_MANAGER_DELETE_NAMESPACE}"